add go get command before install in cli README.md
gochain/gofs pull request #32
Opened 2019-09-19 17:00 UTC by pepijnblom

I had to run the `go get` command first before being able to install, should probably be added to the README.md

2019-09-19 18:26 UTC, jmank88 requested changes

2019-09-19 18:26 UTC, jmank88 commented on cmd/gofs/README.md
> +> go get github.com/gochain/gofs/cmd/gofs
I think we can actually do just `go get -u github.com/gochain/gofs/cmd/gofs`, and drop the `go install`.

2019-09-20 06:19 UTC, pepijnblom commented on cmd/gofs/README.md
> +> go get github.com/gochain/gofs/cmd/gofs
Interesting. I was using the `golang:alpine` Docker image and if you don't have `build-base` installed it doesn't actually install. I started a fresh container and pre-installed `build-base` before running `go get -u` and it did install.

2019-09-20 12:20 UTC, jmank88 commented on cmd/gofs/README.md
> +> go get github.com/gochain/gofs/cmd/gofs
Indeed, this is the min requirements I was able to get working:
```
FROM golang:alpine
RUN apk --no-cache add build-base git gcc
RUN go get -u github.com/gochain/gofs
```
Since this is the 'quickest' install, I think that just `go get -u github.com/gochain/gofs/cmd/gofs` is fine, and I will add docs about the requirements for installing in any case.

2023-03-24 11:03 UTC, closed without merging